require 'buildr/scala'

repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.remote << "http://repository.jboss.org/nexus/content/groups/public/"

NETTY = 'org.jboss.netty:netty:jar:3.2.2.Final'

define "megrez-agent" do
  project.version = '1.0.0'
  project.group = 'megrez'

  compile.with NETTY
  test.using :scalatest

  package(:jar)
  
  task :git_add_untracked => :clean do
	status = `git status`
	untracked_lines = status.split("\n").select{|line| line =~ /^#\t/}.reject{|line| line =~ /^#\t.+:/}.map do |line|
  		line.split("\t")
	end.map{|pair| pair.last}

	untracked_lines.each{|line| puts line}
	cmd = "git add #{untracked_lines.join(' ')}"
	system cmd
  end
end
